# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tstreaming\"\x1d\n\nInferInput\x12\x0f\n\x07prompts\x18\x02 \x03(\t\"*\n\x0bInferOutput\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\r\n\x05texts\x18\x03 \x03(\t2\x96\x01\n\x0cLLaMAService\x12;\n\x08Generate\x12\x15.streaming.InferInput\x1a\x16.streaming.InferOutput\"\x00\x12I\n\x14GenerateServerStream\x12\x15.streaming.InferInput\x1a\x16.streaming.InferOutput\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFERINPUT._serialized_start=30
  _INFERINPUT._serialized_end=59
  _INFEROUTPUT._serialized_start=61
  _INFEROUTPUT._serialized_end=103
  _LLAMASERVICE._serialized_start=106
  _LLAMASERVICE._serialized_end=256
# @@protoc_insertion_point(module_scope)
