# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\"\x1d\n\nInferInput\x12\x0f\n\x07prompts\x18\x01 \x01(\t\"\x1b\n\x0bInferOutput\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x17\n\tSessionID\x12\n\n\x02id\x18\x01 \x01(\x03\x32\x7f\n\x0cLLaMAService\x12\'\n\x08generate\x12\x0b.InferInput\x1a\x0c.InferOutput\"\x00\x12#\n\x06\x63ommit\x12\x0b.InferInput\x1a\n.SessionID\"\x00\x12!\n\x03get\x12\n.SessionID\x1a\x0c.InferOutput\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFERINPUT._serialized_start=19
  _INFERINPUT._serialized_end=48
  _INFEROUTPUT._serialized_start=50
  _INFEROUTPUT._serialized_end=77
  _SESSIONID._serialized_start=79
  _SESSIONID._serialized_end=102
  _LLAMASERVICE._serialized_start=104
  _LLAMASERVICE._serialized_end=231
# @@protoc_insertion_point(module_scope)
